version: '3'

services:
  discord-smtp:
    image: nullcosmos/discord-smtp-server
    build:
      context: .
    container_name: discord-smtp
    ports:
      - 25:25
    environment:
      PORT: 25
      DISCORD_WEBHOOK_URI: $DISCORD_WEBHOOK_URI
      SMTP_USERNAME: $SMTP_USERNAME
      SMTP_PASSWORD: $SMTP_PASSWORD
    volumes:
      - ./message.tt:/message.tt:ro

  test:
    image: nullcosmos/discord-smtp-server-test
    build:
      context: .
      target: test
    container_name: discord-smtp-test
    volumes:
      - ./message.tt:/message.tt:ro
      - ./:/test:ro
    profiles:
      - test